import chromadb
import json
import os
from sentence_transformers import SentenceTransformer

# Initialize
client = chromadb.PersistentClient(path="./data/rag")
model = SentenceTransformer('all-MiniLM-L6-v2')

# Create collections
fraud_collection = client.get_or_create_collection("fraud_patterns")
standards_collection = client.get_or_create_collection("document_standards")

def index_case_logs():
    logs_dir = "./case_logs"
    if not os.path.exists(logs_dir):
        print("No case_logs folder found.")
        return

    files = [f for f in os.listdir(logs_dir) if f.endswith('.json')]
    print(f"Indexing {len(files)} case logs...")

    for i, filename in enumerate(files):
        filepath = os.path.join(logs_dir, filename)
        with open(filepath, 'r') as f:
            try:
                data = json.load(f)
            except:
                continue

        text = json.dumps(data, indent=2)
        embedding = model.encode(text).tolist()

        fraud_collection.upsert(
            ids=[filename],
            embeddings=[embedding],
            documents=[text],
            metadatas=[{"source": filename}]
        )
        print(f"  Indexed: {filename}")

    print(f"Done. {len(files)} fraud patterns indexed.")

def index_document_standards():
    standards = [
        {
            "id": "indian_passport",
            "text": """Indian Passport Standards:
            - MRZ Type: TD3 (2 lines, 44 chars each)
            - MRZ Line 1: P<IND followed by surname<<given names
            - MRZ Line 2: passport number (9 chars) + check digit + IND + DOB (YYMMDD) + check digit + sex + expiry (YYMMDD) + check digit + personal number + check digit + composite check digit
            - Fields: Surname, Given Names, Nationality (IND), Date of Birth, Sex, Place of Birth, Date of Issue, Date of Expiry, Place of Issue
            - Valid expiry: 10 years from issue for adults, 5 years for minors
            - Passport number format: alphanumeric, starts with letter, 8 chars total
            - Security features: UV reactive ink, hologram, microtext, laser perforation"""
        },
        {
            "id": "indian_pan",
            "text": """Indian PAN Card Standards:
            - Format: AAAAA9999A (5 letters + 4 digits + 1 letter)
            - 4th character indicates taxpayer type: P=individual, C=company, H=HUF, F=firm, A=AOP, B=BOI, G=government, J=artificial juridical, L=local authority, T=trust
            - 5th character is first letter of surname for individuals
            - Fields: Name, Father's Name, Date of Birth, PAN Number, Signature
            - Issuing authority: Income Tax Department of India
            - Card dimensions: 85.6mm x 53.98mm (standard credit card size)"""
        },
        {
            "id": "indian_aadhaar",
            "text": """Indian Aadhaar Card Standards:
            - Aadhaar number: 12 digits, generated by UIDAI
            - Verhoeff algorithm check digit on last digit
            - First digit is never 0 or 1
            - Fields: Name, Date of Birth, Gender, Address, Aadhaar Number, QR Code
            - QR Code contains: name, gender, DOB, address (encrypted)
            - VID (Virtual ID): 16 digit temporary ID
            - Format on card: XXXX XXXX XXXX (groups of 4)
            - Issuing authority: UIDAI (Unique Identification Authority of India)"""
        },
        {
            "id": "us_passport",
            "text": """US Passport Standards:
            - MRZ Type: TD3 (2 lines, 44 chars each)
            - MRZ Line 1: P<USA followed by surname<<given names
            - Passport number: 9 alphanumeric characters
            - Fields: Surname, Given Names, Nationality (USA), Date of Birth, Sex, Place of Birth, Issue Date, Expiry Date, Passport Number
            - Valid expiry: 10 years for adults (16+), 5 years for minors
            - Security features: holographic laminate, UV ink, RFID chip (ePassport), laser engraved photo"""
        },
        {
            "id": "schengen_visa",
            "text": """Schengen Visa Standards:
            - Visa sticker dimensions: 105mm x 74mm
            - MRZ: 2 lines, 36 chars each (TD1 format)
            - Fields: Valid From, Valid Until, Duration of Stay, Number of Entries, Issued In, On Date, Number, Type, Remarks
            - Entry types: single (01), double (02), multiple (MULT)
            - Holographic kinegram with EU stars
            - Color shifting ink on visa number
            - Microtext on borders
            - Countries: 26 Schengen member states"""
        },
        {
            "id": "mrz_check_digits",
            "text": """MRZ Check Digit Algorithm (ICAO Doc 9303):
            - Character values: A=10, B=11...Z=35, 0-9=face value, <  =0
            - Weights: 7, 3, 1 repeating
            - Multiply each character value by its weight
            - Sum all products
            - Check digit = sum modulo 10
            - Applied to: passport number, date of birth, expiry date, personal number, composite (line 2 chars 1-43)
            - Filler character < has value 0"""
        },
        {
            "id": "document_security_features",
            "text": """Common Document Security Features:
            - UV fluorescent ink: glows under 365nm UV light
            - Microtext: text smaller than 0.2mm, blurs when photocopied
            - Guilloché patterns: complex geometric backgrounds, create Moiré when copied
            - Rainbow printing: smooth color gradient, impossible on CMYK printers
            - Hologram: kinegram that shifts color and pattern when tilted
            - Laser perforation: holes through all pages, conical shape
            - Security threads: metallic strips woven through paper
            - Watermarks: visible when held to light
            - Intaglio printing: raised ink texture, tactile feel
            - RFID chip: biometric data in ePassports (ICAO 9303 Part 9)"""
        }
    ]

    print(f"Indexing {len(standards)} document standards...")

    for standard in standards:
        embedding = model.encode(standard['text']).tolist()
        standards_collection.upsert(
            ids=[standard['id']],
            embeddings=[embedding],
            documents=[standard['text']],
            metadatas=[{"type": standard['id']}]
        )
        print(f"  Indexed: {standard['id']}")

    print(f"Done. {len(standards)} standards indexed.")

if __name__ == "__main__":
    print("KAVACH RAG INDEXER")
    print("==================")
    index_document_standards()
    index_case_logs()
    print("\nAll done. RAG knowledge base ready.")